const { Octokit } = require("@octokit/rest");

// install with npm install @octokit/rest
const octokit = new Octokit({
  auth: process.env.GITHUB_TOKEN
});

// Create an issue comment
octokit.rest.issues.createComment({
  owner: 'paolodragol',
  repo: 'wandb-cicd',
  issue_number: 5,
  body: 'Hi there, this is a comment generated by `octokit.js`',
});
