name: assignment-cicd
on: issue_comment

permissions:
  contents: read
  issues: write
  pull-requests: write

env:
  WANDB_COMMENT: "/wandb" 

jobs:
  see-comment:
    # this filters for only comments made on a pull request
    if: (github.event.issue.pull_request != null)
    runs-on: ubuntu-latest
    steps:
    - name: see payload
      run: echo "PAYLOAD:\n${PAYLOAD}\n"
      env:
        PAYLOAD: ${{ toJSON(github.event) }}
        
    - name: filter for comment
      id: filter
      if: contains(github.event.comment.body, env.WANDB_COMMENT)
      run: echo "wandb comment detected"

    - name: get repo contents
      uses: actions/checkout@v3

    - name: install dependencies
      run: pip install ghapi wandb

    - name: get id value from the comment
      id: get-id-value
      shell: python
      run: |
        import re, os
        comment = os.getenv('PR_COMMENT', '')
        match = re.search('/wandb[\s+](\S+)', comment)

        with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
          if match:
            print(f'VAL_FOUND=true', file=f)
            print(f'RUN_ID={match.group(1)}', file=f)
          else:
            print(f'VAL_FOUND=false', file=f)
      env:
        PR_COMMENT: ${{ github.event.comment.body }}

    - name: generate wandb report
      if: steps.get-id-value.outputs.VAL_FOUND == 'true'
      id: wandb-report
      run: python ./client/compare_runs.py
      env:
        WANDB_ENTITY: paolodragol
        WANDB_PROJECT: cicd_quickstart
        BASELINE_TAG: baseline
        RUN_ID: "${{ steps.get-runid-value.outputs.RUN_ID }}"
        WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}

    - name: comment on pr with the GitHub API
      uses: actions/github-script@v6
      if: steps.wandb-report.outcome == 'success' 
      with:
        script: |
           var msg = `A comparison between the linked run and baseline is available [in this report](${process.env.REPORT_URL})`
           github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: msg
            });
      env:
        REPORT_URL: "${{ steps.wandb-report.outputs.REPORT_URL }}"
        
